//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsAffairsDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice_payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public invoice_payment()
        {
            this.invoice_payment1 = new HashSet<invoice_payment>();
            this.payment_details = new HashSet<payment_details>();
        }
    
        public int id { get; set; }
        public int student { get; set; }
        public System.DateTime date { get; set; }
        public decimal total_cost { get; set; }
        public decimal paid { get; set; }
        public decimal remaining { get; set; }
        public Nullable<int> previous_payment { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice_payment> invoice_payment1 { get; set; }
        public virtual invoice_payment invoice_payment2 { get; set; }
        public virtual StudentsMain StudentsMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_details> payment_details { get; set; }
    }
}
