//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsAffairsDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSubjectEnroll
    {
        public int SSID { get; set; }
        public int StdCode { get; set; }
        public int SubjectID { get; set; }
        public string StudyYear { get; set; }
    
        public virtual StudentsMain StudentsMain { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
