//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsAffairsDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAccount
    {
        public int StdCode { get; set; }
        public string StdEmail { get; set; }
        public string StdPassword { get; set; }
        public string StdStatus { get; set; }
    
        public virtual StudentsMain StudentsMain { get; set; }
    }
}
