//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsAffairsDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsMainCustom
    {
        public int StdCodeCustom { get; set; }
        public Nullable<bool> StdArabicFristName { get; set; }
        public Nullable<bool> StdArabicMiddleName { get; set; }
        public Nullable<bool> StdArabicLastName { get; set; }
        public Nullable<bool> StdArabicFamilyName { get; set; }
        public Nullable<bool> StdEnglishFristName { get; set; }
        public Nullable<bool> StdEnglishMiddleName { get; set; }
        public Nullable<bool> StdEnglishLastName { get; set; }
        public Nullable<bool> StdEnglishFamilyName { get; set; }
        public Nullable<bool> StdMotherArabicName { get; set; }
        public Nullable<bool> StdMotherEnglishName { get; set; }
        public Nullable<bool> StdFatherMobilePhone { get; set; }
        public Nullable<bool> StdMotherMobilePhone { get; set; }
        public Nullable<bool> StdFatherEmail { get; set; }
        public Nullable<bool> StdMotherEmail { get; set; }
        public Nullable<bool> StdFatherNationality { get; set; }
        public Nullable<bool> StdMotherNationality { get; set; }
        public Nullable<bool> StdFatherSpokenLanguage { get; set; }
        public Nullable<bool> StdMotherSpokenLanguage { get; set; }
        public Nullable<bool> StdFatherJob { get; set; }
        public Nullable<bool> StdMotherJob { get; set; }
        public Nullable<bool> StdFatherQualification { get; set; }
        public Nullable<bool> StdMotherQualification { get; set; }
        public Nullable<bool> StdStudentsAffairs1 { get; set; }
        public Nullable<bool> StdStudentsAffairs2 { get; set; }
        public Nullable<bool> StdBirthCode { get; set; }
        public Nullable<bool> StdAddressGov { get; set; }
        public Nullable<bool> StdEmergencyContact { get; set; }
        public Nullable<bool> StdEmergencyPhone { get; set; }
        public Nullable<bool> StdBOD { get; set; }
        public Nullable<bool> StdBirthPlace { get; set; }
        public Nullable<bool> StdGender { get; set; }
        public Nullable<bool> StdReligion { get; set; }
        public Nullable<bool> StdFatherNID { get; set; }
        public Nullable<bool> StdMotherNID { get; set; }
        public Nullable<bool> StdCity { get; set; }
        public Nullable<bool> StdAddress { get; set; }
        public Nullable<bool> StdNID { get; set; }
        public Nullable<bool> StdSchoolID { get; set; }
        public Nullable<bool> StdClassID { get; set; }
        public Nullable<bool> StdNationality { get; set; }
        public Nullable<bool> StdStatus { get; set; }
        public Nullable<bool> StdJoinYear { get; set; }
        public Nullable<bool> StdStaffSon { get; set; }
        public Nullable<bool> StdLegalGuardianship { get; set; }
        public Nullable<bool> StdParentsSeparated { get; set; }
    }
}
